// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/choices": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "choices"
                ],
                "summary": "Create a choice",
                "parameters": [
                    {
                        "description": "Choice payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateChoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ChoiceCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/consequences": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consequences"
                ],
                "summary": "Create a consequence",
                "parameters": [
                    {
                        "description": "Consequence payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateConsequenceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ConsequenceCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/consequences/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "consequences"
                ],
                "summary": "Update a consequence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consequence UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Consequence payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateConsequenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConsequenceCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "consequences"
                ],
                "summary": "Delete a consequence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consequence UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/explanations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "explanations"
                ],
                "summary": "Create an explanation",
                "parameters": [
                    {
                        "description": "Explanation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateExplanationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ExplanationCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/explanations/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "explanations"
                ],
                "summary": "Update an explanation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Explanation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Explanation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateExplanationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ExplanationCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "explanations"
                ],
                "summary": "Delete an explanation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Explanation UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/impacts": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "impacts"
                ],
                "summary": "Create an impact",
                "parameters": [
                    {
                        "description": "Impact payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateImpactRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ImpactCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/impacts/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "impacts"
                ],
                "summary": "Update an impact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Impact UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Impact payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateImpactRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ImpactCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "impacts"
                ],
                "summary": "Delete an impact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Impact UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scenarios": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scenarios"
                ],
                "summary": "List scenarios",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ScenarioPaginationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scenarios"
                ],
                "summary": "Create a scenario",
                "parameters": [
                    {
                        "description": "Scenario payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateScenarioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scenarios/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scenarios"
                ],
                "summary": "Get a scenario by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scenario UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ScenarioResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Start a new session",
                "parameters": [
                    {
                        "description": "Session payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sessions/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get session by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/submit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Submit a choice for a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Choice payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SubmitChoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SubmitChoiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get session summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SessionSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/steps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "List steps",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StepPaginationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Create a step",
                "parameters": [
                    {
                        "description": "Step payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateStepRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.StepResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ChoiceCreatedResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "nextStepId": {
                    "type": "string"
                },
                "stepId": {
                    "type": "string"
                }
            }
        },
        "dto.ChoiceResponse": {
            "type": "object",
            "properties": {
                "consequences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ConsequencesResponse"
                    }
                },
                "explanations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "impacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ImpactResponse"
                    }
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "nextStepId": {
                    "type": "string"
                }
            }
        },
        "dto.ConsequenceCreatedResponse": {
            "type": "object",
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "keys": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "dto.ConsequencesResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "dto.CreateChoiceRequest": {
            "type": "object",
            "required": [
                "label",
                "stepId"
            ],
            "properties": {
                "isCorrect": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string",
                    "minLength": 1
                },
                "nextStepId": {
                    "type": "string"
                },
                "stepId": {
                    "type": "string"
                }
            }
        },
        "dto.CreateConsequenceRequest": {
            "type": "object",
            "required": [
                "choiceId",
                "keys",
                "type"
            ],
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "keys": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "dto.CreateExplanationRequest": {
            "type": "object",
            "required": [
                "choiceId",
                "content",
                "level"
            ],
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "content": {
                    "type": "string",
                    "minLength": 1
                },
                "level": {
                    "type": "string",
                    "enum": [
                        "beginner",
                        "intermediate",
                        "advanced"
                    ]
                }
            }
        },
        "dto.CreateImpactRequest": {
            "type": "object",
            "required": [
                "choiceId",
                "metric",
                "type"
            ],
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "metric": {
                    "type": "string",
                    "enum": [
                        "latency",
                        "cost",
                        "scalability"
                    ]
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "add",
                        "multiply",
                        "set"
                    ]
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dto.CreateScenarioRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "difficulty": {
                    "type": "string",
                    "enum": [
                        "easy",
                        "medium",
                        "hard"
                    ]
                },
                "start_step_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "dto.CreateStepRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "context": {
                    "type": "string",
                    "maxLength": 500
                },
                "orderIndex": {
                    "type": "integer"
                },
                "question": {
                    "type": "string",
                    "minLength": 3
                },
                "scenarioID": {
                    "type": "string"
                }
            }
        },
        "dto.ExplanationCreatedResponse": {
            "type": "object",
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                }
            }
        },
        "dto.ImpactCreatedResponse": {
            "type": "object",
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metric": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dto.ImpactResponse": {
            "type": "object",
            "properties": {
                "metric": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dto.ScenarioPaginationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ScenarioResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "dto.ScenarioResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StepResponse"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.SessionResponse": {
            "type": "object",
            "properties": {
                "currentStep": {
                    "$ref": "#/definitions/dto.StepResponse"
                },
                "flags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "id": {
                    "type": "string"
                },
                "metrics": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "scenarioId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.SessionSummaryResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserChoiceSummary"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "flags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "id": {
                    "type": "string"
                },
                "metrics": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "scenarioId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.StartSessionRequest": {
            "type": "object",
            "required": [
                "scenarioId",
                "userId"
            ],
            "properties": {
                "scenarioId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.StepPaginationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StepResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "dto.StepResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChoiceResponse"
                    }
                },
                "context": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "dto.SubmitChoiceRequest": {
            "type": "object",
            "required": [
                "choiceId"
            ],
            "properties": {
                "choiceId": {
                    "type": "string"
                }
            }
        },
        "dto.SubmitChoiceResponse": {
            "type": "object",
            "properties": {
                "explanations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "feedback": {
                    "type": "string"
                },
                "isCompleted": {
                    "type": "boolean"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "metrics": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "nextStep": {
                    "$ref": "#/definitions/dto.StepResponse"
                }
            }
        },
        "dto.UpdateConsequenceRequest": {
            "type": "object",
            "required": [
                "keys",
                "type"
            ],
            "properties": {
                "keys": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateExplanationRequest": {
            "type": "object",
            "required": [
                "content",
                "level"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 1
                },
                "level": {
                    "type": "string",
                    "enum": [
                        "beginner",
                        "intermediate",
                        "advanced"
                    ]
                }
            }
        },
        "dto.UpdateImpactRequest": {
            "type": "object",
            "required": [
                "metric",
                "type"
            ],
            "properties": {
                "metric": {
                    "type": "string",
                    "enum": [
                        "latency",
                        "cost",
                        "scalability"
                    ]
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "add",
                        "multiply",
                        "set"
                    ]
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dto.UserChoiceSummary": {
            "type": "object",
            "properties": {
                "choiceId": {
                    "type": "string"
                },
                "explanations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "stepId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "System Design Lab API",
	Description:      "Guided System Design Playground — learn system design through decisions and consequences.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
