// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: choice.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createChoice = `-- name: CreateChoice :one
INSERT INTO choices (id, step_id, label, next_step_id, is_correct)
VALUES ($1::uuid, $2::uuid, $3, $4, $5)
RETURNING id, step_id, label, next_step_id, is_correct, created_at
`

type CreateChoiceParams struct {
	Column1    uuid.UUID
	Column2    uuid.UUID
	Label      string
	NextStepID uuid.UUID
	IsCorrect  bool
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, createChoice,
		arg.Column1,
		arg.Column2,
		arg.Label,
		arg.NextStepID,
		arg.IsCorrect,
	)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Label,
		&i.NextStepID,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChoice = `-- name: DeleteChoice :exec
DELETE FROM choices
WHERE id = $1::uuid
`

func (q *Queries) DeleteChoice(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChoice, dollar_1)
	return err
}

const getChoice = `-- name: GetChoice :one
SELECT
    id,
    step_id,
    label,
    next_step_id,
    is_correct
FROM choices
WHERE id = $1::uuid
`

type GetChoiceRow struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	Label      string
	NextStepID uuid.UUID
	IsCorrect  bool
}

func (q *Queries) GetChoice(ctx context.Context, dollar_1 uuid.UUID) (GetChoiceRow, error) {
	row := q.db.QueryRow(ctx, getChoice, dollar_1)
	var i GetChoiceRow
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Label,
		&i.NextStepID,
		&i.IsCorrect,
	)
	return i, err
}

const getChoicesByStepIDs = `-- name: GetChoicesByStepIDs :many

SELECT
    id,
    step_id,
    label,
    next_step_id,
    is_correct
FROM choices
WHERE step_id = ANY($1::uuid[])
ORDER BY step_id, created_at
`

type GetChoicesByStepIDsRow struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	Label      string
	NextStepID uuid.UUID
	IsCorrect  bool
}

func (q *Queries) GetChoicesByStepIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetChoicesByStepIDsRow, error) {
	rows, err := q.db.Query(ctx, getChoicesByStepIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChoicesByStepIDsRow
	for rows.Next() {
		var i GetChoicesByStepIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Label,
			&i.NextStepID,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChoice = `-- name: UpdateChoice :one
UPDATE choices
SET label = $2, next_step_id = $3, is_correct = $4
WHERE id = $1::uuid
RETURNING id, step_id, label, next_step_id, is_correct, created_at
`

type UpdateChoiceParams struct {
	Column1    uuid.UUID
	Label      string
	NextStepID uuid.UUID
	IsCorrect  bool
}

func (q *Queries) UpdateChoice(ctx context.Context, arg UpdateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, updateChoice,
		arg.Column1,
		arg.Label,
		arg.NextStepID,
		arg.IsCorrect,
	)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Label,
		&i.NextStepID,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}
