// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conditions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCondition = `-- name: CreateCondition :one

INSERT INTO conditions (
    id,
    step_id,
    type,
    metric,
    operator,
    value,
    float_key,
    choice_id
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::condition_type,
    $4::impact_metric,
    $5::text,
    $6::float,
    $7::text,
    $8::uuid
)
RETURNING id, step_id, type, metric, operator, value, float_key, choice_id
`

type CreateConditionParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Column3 ConditionType
	Column4 ImpactMetric
	Column5 string
	Column6 float64
	Column7 string
	Column8 uuid.UUID
}

type CreateConditionRow struct {
	ID       uuid.UUID
	StepID   uuid.UUID
	Type     ConditionType
	Metric   NullImpactMetric
	Operator pgtype.Text
	Value    pgtype.Float8
	FloatKey pgtype.Text
	ChoiceID uuid.UUID
}

func (q *Queries) CreateCondition(ctx context.Context, arg CreateConditionParams) (CreateConditionRow, error) {
	row := q.db.QueryRow(ctx, createCondition,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var i CreateConditionRow
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Type,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.FloatKey,
		&i.ChoiceID,
	)
	return i, err
}

const deleteCondition = `-- name: DeleteCondition :exec
DELETE FROM conditions
WHERE id = $1::uuid
`

func (q *Queries) DeleteCondition(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCondition, dollar_1)
	return err
}

const getCondition = `-- name: GetCondition :one
SELECT
    id,
    step_id,
    type,
    metric,
    operator,
    value,
    float_key,
    choice_id
FROM conditions
WHERE id = $1::uuid
`

type GetConditionRow struct {
	ID       uuid.UUID
	StepID   uuid.UUID
	Type     ConditionType
	Metric   NullImpactMetric
	Operator pgtype.Text
	Value    pgtype.Float8
	FloatKey pgtype.Text
	ChoiceID uuid.UUID
}

func (q *Queries) GetCondition(ctx context.Context, dollar_1 uuid.UUID) (GetConditionRow, error) {
	row := q.db.QueryRow(ctx, getCondition, dollar_1)
	var i GetConditionRow
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Type,
		&i.Metric,
		&i.Operator,
		&i.Value,
		&i.FloatKey,
		&i.ChoiceID,
	)
	return i, err
}

const getConditionsByStep = `-- name: GetConditionsByStep :many
SELECT
    id,
    step_id,
    type,
    metric,
    operator,
    value,
    float_key,
    choice_id
FROM conditions
WHERE step_id = $1::uuid
ORDER BY created_at
`

type GetConditionsByStepRow struct {
	ID       uuid.UUID
	StepID   uuid.UUID
	Type     ConditionType
	Metric   NullImpactMetric
	Operator pgtype.Text
	Value    pgtype.Float8
	FloatKey pgtype.Text
	ChoiceID uuid.UUID
}

func (q *Queries) GetConditionsByStep(ctx context.Context, dollar_1 uuid.UUID) ([]GetConditionsByStepRow, error) {
	rows, err := q.db.Query(ctx, getConditionsByStep, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConditionsByStepRow
	for rows.Next() {
		var i GetConditionsByStepRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Type,
			&i.Metric,
			&i.Operator,
			&i.Value,
			&i.FloatKey,
			&i.ChoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
