// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consequence.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createConsequence = `-- name: CreateConsequence :one

INSERT INTO consequences (
    id,
    choice_id,
    type,
    keys,
    value
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5
)
RETURNING id, choice_id, type, keys, value
`

type CreateConsequenceParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Type    string
	Keys    string
	Value   bool
}

type CreateConsequenceRow struct {
	ID       uuid.UUID
	ChoiceID uuid.UUID
	Type     string
	Keys     string
	Value    bool
}

func (q *Queries) CreateConsequence(ctx context.Context, arg CreateConsequenceParams) (CreateConsequenceRow, error) {
	row := q.db.QueryRow(ctx, createConsequence,
		arg.Column1,
		arg.Column2,
		arg.Type,
		arg.Keys,
		arg.Value,
	)
	var i CreateConsequenceRow
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Type,
		&i.Keys,
		&i.Value,
	)
	return i, err
}

const deleteConsequence = `-- name: DeleteConsequence :exec
DELETE FROM consequences
WHERE id = $1::uuid
`

func (q *Queries) DeleteConsequence(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConsequence, dollar_1)
	return err
}

const getConsequence = `-- name: GetConsequence :one

SELECT
    id,
    choice_id,
    type,
    keys,
    value
FROM consequences
WHERE choice_id = $1::uuid
`

type GetConsequenceRow struct {
	ID       uuid.UUID
	ChoiceID uuid.UUID
	Type     string
	Keys     string
	Value    bool
}

func (q *Queries) GetConsequence(ctx context.Context, dollar_1 uuid.UUID) (GetConsequenceRow, error) {
	row := q.db.QueryRow(ctx, getConsequence, dollar_1)
	var i GetConsequenceRow
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Type,
		&i.Keys,
		&i.Value,
	)
	return i, err
}

const getConsequencesByChoiceIDs = `-- name: GetConsequencesByChoiceIDs :many

SELECT
    choice_id,
    keys,
    value
FROM consequences
WHERE choice_id = ANY($1::uuid[])
`

type GetConsequencesByChoiceIDsRow struct {
	ChoiceID uuid.UUID
	Keys     string
	Value    bool
}

func (q *Queries) GetConsequencesByChoiceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetConsequencesByChoiceIDsRow, error) {
	rows, err := q.db.Query(ctx, getConsequencesByChoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConsequencesByChoiceIDsRow
	for rows.Next() {
		var i GetConsequencesByChoiceIDsRow
		if err := rows.Scan(&i.ChoiceID, &i.Keys, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsequence = `-- name: UpdateConsequence :one
UPDATE consequences
SET
    type = $2,
    keys = $3,
    value = $4
WHERE id = $1::uuid
RETURNING id, choice_id, type, keys, value, created_at
`

type UpdateConsequenceParams struct {
	Column1 uuid.UUID
	Type    string
	Keys    string
	Value   bool
}

func (q *Queries) UpdateConsequence(ctx context.Context, arg UpdateConsequenceParams) (Consequence, error) {
	row := q.db.QueryRow(ctx, updateConsequence,
		arg.Column1,
		arg.Type,
		arg.Keys,
		arg.Value,
	)
	var i Consequence
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Type,
		&i.Keys,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
