// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: explanation.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createExplanation = `-- name: CreateExplanation :one
INSERT INTO explanations (
    id,
    choice_id,
    level,
    content
) VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4
) RETURNING id, choice_id, level, content, created_at
`

type CreateExplanationParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Level   ExplanationLevel
	Content string
}

func (q *Queries) CreateExplanation(ctx context.Context, arg CreateExplanationParams) (Explanation, error) {
	row := q.db.QueryRow(ctx, createExplanation,
		arg.Column1,
		arg.Column2,
		arg.Level,
		arg.Content,
	)
	var i Explanation
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Level,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExplanation = `-- name: DeleteExplanation :exec
DELETE FROM explanations
WHERE id = $1::uuid
`

func (q *Queries) DeleteExplanation(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExplanation, dollar_1)
	return err
}

const getExplanationsByChoiceIDs = `-- name: GetExplanationsByChoiceIDs :many

SELECT
    choice_id,
    level,
    content
FROM explanations
WHERE choice_id = ANY($1::uuid[])
`

type GetExplanationsByChoiceIDsRow struct {
	ChoiceID uuid.UUID
	Level    ExplanationLevel
	Content  string
}

func (q *Queries) GetExplanationsByChoiceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetExplanationsByChoiceIDsRow, error) {
	rows, err := q.db.Query(ctx, getExplanationsByChoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExplanationsByChoiceIDsRow
	for rows.Next() {
		var i GetExplanationsByChoiceIDsRow
		if err := rows.Scan(&i.ChoiceID, &i.Level, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExplanation = `-- name: UpdateExplanation :one
UPDATE explanations
SET
    level = $2,
    content = $3
WHERE id = $1::uuid
RETURNING id, choice_id, level, content, created_at
`

type UpdateExplanationParams struct {
	Column1 uuid.UUID
	Level   ExplanationLevel
	Content string
}

func (q *Queries) UpdateExplanation(ctx context.Context, arg UpdateExplanationParams) (Explanation, error) {
	row := q.db.QueryRow(ctx, updateExplanation, arg.Column1, arg.Level, arg.Content)
	var i Explanation
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Level,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
