// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: impact.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createImpact = `-- name: CreateImpact :one
INSERT INTO impacts (
    id,
    choice_id,
    metric,
    type,
    value
) VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5
) RETURNING id, choice_id, metric, type, value, created_at
`

type CreateImpactParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Metric  ImpactMetric
	Type    ImpactType
	Value   float64
}

func (q *Queries) CreateImpact(ctx context.Context, arg CreateImpactParams) (Impact, error) {
	row := q.db.QueryRow(ctx, createImpact,
		arg.Column1,
		arg.Column2,
		arg.Metric,
		arg.Type,
		arg.Value,
	)
	var i Impact
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Metric,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImpact = `-- name: DeleteImpact :exec
DELETE FROM impacts
WHERE id = $1::uuid
`

func (q *Queries) DeleteImpact(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImpact, dollar_1)
	return err
}

const getImpactsByChoiceIDs = `-- name: GetImpactsByChoiceIDs :many

SELECT
    choice_id,
    metric,
    type,
    value
FROM impacts
WHERE choice_id = ANY($1::uuid[])
`

type GetImpactsByChoiceIDsRow struct {
	ChoiceID uuid.UUID
	Metric   ImpactMetric
	Type     ImpactType
	Value    float64
}

func (q *Queries) GetImpactsByChoiceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetImpactsByChoiceIDsRow, error) {
	rows, err := q.db.Query(ctx, getImpactsByChoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImpactsByChoiceIDsRow
	for rows.Next() {
		var i GetImpactsByChoiceIDsRow
		if err := rows.Scan(
			&i.ChoiceID,
			&i.Metric,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImpact = `-- name: UpdateImpact :one
UPDATE impacts
SET
    metric = $2,
    type = $3,
    value = $4
WHERE id = $1::uuid
RETURNING id, choice_id, metric, type, value, created_at
`

type UpdateImpactParams struct {
	Column1 uuid.UUID
	Metric  ImpactMetric
	Type    ImpactType
	Value   float64
}

func (q *Queries) UpdateImpact(ctx context.Context, arg UpdateImpactParams) (Impact, error) {
	row := q.db.QueryRow(ctx, updateImpact,
		arg.Column1,
		arg.Metric,
		arg.Type,
		arg.Value,
	)
	var i Impact
	err := row.Scan(
		&i.ID,
		&i.ChoiceID,
		&i.Metric,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
