// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLeaderboardByScenario = `-- name: GetLeaderboardByScenario :many
SELECT
    us.id         AS session_id,
    us.user_id,
    u.username,
    us.created_at,
    us.completed_at,
    COUNT(uc.id)::int                                       AS total_choices,
    COUNT(CASE WHEN c.is_correct THEN 1 END)::int           AS correct_choices
FROM user_sessions us
JOIN users u        ON u.id  = us.user_id
JOIN user_choices uc ON uc.session_id = us.id
JOIN choices c       ON c.id  = uc.choice_id
WHERE us.scenario_id = $1::uuid
  AND us.status      = 'completed'
GROUP BY us.id, us.user_id, u.username
ORDER BY correct_choices DESC, us.completed_at ASC
LIMIT $2::int
`

type GetLeaderboardByScenarioParams struct {
	ScenarioID uuid.UUID
	TopN       int32
}

type GetLeaderboardByScenarioRow struct {
	SessionID      uuid.UUID
	UserID         uuid.UUID
	Username       string
	CreatedAt      pgtype.Timestamp
	CompletedAt    pgtype.Timestamp
	TotalChoices   int32
	CorrectChoices int32
}

func (q *Queries) GetLeaderboardByScenario(ctx context.Context, arg GetLeaderboardByScenarioParams) ([]GetLeaderboardByScenarioRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByScenario, arg.ScenarioID, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardByScenarioRow
	for rows.Next() {
		var i GetLeaderboardByScenarioRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.Username,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.TotalChoices,
			&i.CorrectChoices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenarioProgressByUser = `-- name: GetScenarioProgressByUser :many
SELECT
    s.id                                                            AS scenario_id,
    s.title,
    s.difficulty,
    COUNT(us.id)::int                                               AS attempts,
    COUNT(CASE WHEN us.status = 'completed' THEN 1 END)::int        AS completions,
    MAX(us.completed_at)                                            AS last_completed_at
FROM scenarios s
LEFT JOIN user_sessions us ON us.scenario_id = s.id AND us.user_id = $1::uuid
GROUP BY s.id, s.title, s.difficulty
ORDER BY s.created_at
`

type GetScenarioProgressByUserRow struct {
	ScenarioID      uuid.UUID
	Title           string
	Difficulty      DifficultyLevel
	Attempts        int32
	Completions     int32
	LastCompletedAt interface{}
}

func (q *Queries) GetScenarioProgressByUser(ctx context.Context, userID uuid.UUID) ([]GetScenarioProgressByUserRow, error) {
	rows, err := q.db.Query(ctx, getScenarioProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScenarioProgressByUserRow
	for rows.Next() {
		var i GetScenarioProgressByUserRow
		if err := rows.Scan(
			&i.ScenarioID,
			&i.Title,
			&i.Difficulty,
			&i.Attempts,
			&i.Completions,
			&i.LastCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionScore = `-- name: GetSessionScore :one
SELECT
    COUNT(uc.id)::int                             AS total_choices,
    COUNT(CASE WHEN c.is_correct THEN 1 END)::int AS correct_choices
FROM user_choices uc
JOIN choices c ON c.id = uc.choice_id
WHERE uc.session_id = $1::uuid
`

type GetSessionScoreRow struct {
	TotalChoices   int32
	CorrectChoices int32
}

func (q *Queries) GetSessionScore(ctx context.Context, sessionID uuid.UUID) (GetSessionScoreRow, error) {
	row := q.db.QueryRow(ctx, getSessionScore, sessionID)
	var i GetSessionScoreRow
	err := row.Scan(&i.TotalChoices, &i.CorrectChoices)
	return i, err
}
