// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConditionType string

const (
	ConditionTypeMetric ConditionType = "metric"
	ConditionTypeFlag   ConditionType = "flag"
	ConditionTypeChoice ConditionType = "choice"
)

func (e *ConditionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConditionType(s)
	case string:
		*e = ConditionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConditionType: %T", src)
	}
	return nil
}

type NullConditionType struct {
	ConditionType ConditionType
	Valid         bool // Valid is true if ConditionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConditionType) Scan(value interface{}) error {
	if value == nil {
		ns.ConditionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConditionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConditionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConditionType), nil
}

type DifficultyLevel string

const (
	DifficultyLevelEasy   DifficultyLevel = "easy"
	DifficultyLevelMedium DifficultyLevel = "medium"
	DifficultyLevelHard   DifficultyLevel = "hard"
)

func (e *DifficultyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DifficultyLevel(s)
	case string:
		*e = DifficultyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for DifficultyLevel: %T", src)
	}
	return nil
}

type NullDifficultyLevel struct {
	DifficultyLevel DifficultyLevel
	Valid           bool // Valid is true if DifficultyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficultyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.DifficultyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DifficultyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficultyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DifficultyLevel), nil
}

type ExplanationLevel string

const (
	ExplanationLevelBeginner     ExplanationLevel = "beginner"
	ExplanationLevelIntermediate ExplanationLevel = "intermediate"
	ExplanationLevelAdvanced     ExplanationLevel = "advanced"
)

func (e *ExplanationLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExplanationLevel(s)
	case string:
		*e = ExplanationLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ExplanationLevel: %T", src)
	}
	return nil
}

type NullExplanationLevel struct {
	ExplanationLevel ExplanationLevel
	Valid            bool // Valid is true if ExplanationLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExplanationLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ExplanationLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExplanationLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExplanationLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExplanationLevel), nil
}

type ImpactMetric string

const (
	ImpactMetricLatency     ImpactMetric = "latency"
	ImpactMetricCost        ImpactMetric = "cost"
	ImpactMetricScalability ImpactMetric = "scalability"
)

func (e *ImpactMetric) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImpactMetric(s)
	case string:
		*e = ImpactMetric(s)
	default:
		return fmt.Errorf("unsupported scan type for ImpactMetric: %T", src)
	}
	return nil
}

type NullImpactMetric struct {
	ImpactMetric ImpactMetric
	Valid        bool // Valid is true if ImpactMetric is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImpactMetric) Scan(value interface{}) error {
	if value == nil {
		ns.ImpactMetric, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImpactMetric.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImpactMetric) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImpactMetric), nil
}

type ImpactType string

const (
	ImpactTypeAdd      ImpactType = "add"
	ImpactTypeMultiply ImpactType = "multiply"
	ImpactTypeSet      ImpactType = "set"
)

func (e *ImpactType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImpactType(s)
	case string:
		*e = ImpactType(s)
	default:
		return fmt.Errorf("unsupported scan type for ImpactType: %T", src)
	}
	return nil
}

type NullImpactType struct {
	ImpactType ImpactType
	Valid      bool // Valid is true if ImpactType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImpactType) Scan(value interface{}) error {
	if value == nil {
		ns.ImpactType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImpactType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImpactType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImpactType), nil
}

type SessionStatus string

const (
	SessionStatusInProgress SessionStatus = "in_progress"
	SessionStatusCompleted  SessionStatus = "completed"
	SessionStatusFailed     SessionStatus = "failed"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus
	Valid         bool // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type Choice struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	Label      string
	NextStepID uuid.UUID
	IsCorrect  bool
	CreatedAt  pgtype.Timestamp
}

type Condition struct {
	ID        uuid.UUID
	StepID    uuid.UUID
	Type      ConditionType
	Metric    NullImpactMetric
	Operator  pgtype.Text
	Value     pgtype.Float8
	FloatKey  pgtype.Text
	ChoiceID  uuid.UUID
	CreatedAt pgtype.Timestamp
}

type Consequence struct {
	ID        uuid.UUID
	ChoiceID  uuid.UUID
	Type      string
	Keys      string
	Value     bool
	CreatedAt pgtype.Timestamp
}

type Explanation struct {
	ID        uuid.UUID
	ChoiceID  uuid.UUID
	Level     ExplanationLevel
	Content   string
	CreatedAt pgtype.Timestamp
}

type Impact struct {
	ID        uuid.UUID
	ChoiceID  uuid.UUID
	Metric    ImpactMetric
	Type      ImpactType
	Value     float64
	CreatedAt pgtype.Timestamp
}

type Scenario struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
	Difficulty  DifficultyLevel
	CreatedAt   pgtype.Timestamp
}

type Step struct {
	ID         uuid.UUID
	ScenarioID uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
	CreatedAt  pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}

type UserChoice struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	StepID    uuid.UUID
	ChoiceID  uuid.UUID
	CreatedAt pgtype.Timestamp
}

type UserSession struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ScenarioID    uuid.UUID
	CurrentStepID uuid.UUID
	Metrics       []byte
	Flags         []byte
	Status        SessionStatus
	CreatedAt     pgtype.Timestamp
}
