// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getChoicesByStepIDs = `-- name: GetChoicesByStepIDs :many

SELECT
    id,
    step_id,
    label,
    next_step_id,
    is_correct
FROM choices
WHERE step_id = ANY($1::uuid[])
`

type GetChoicesByStepIDsRow struct {
	ID         uuid.UUID
	StepID     uuid.UUID
	Label      string
	NextStepID uuid.UUID
	IsCorrect  bool
}

func (q *Queries) GetChoicesByStepIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetChoicesByStepIDsRow, error) {
	rows, err := q.db.Query(ctx, getChoicesByStepIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChoicesByStepIDsRow
	for rows.Next() {
		var i GetChoicesByStepIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Label,
			&i.NextStepID,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConsequencesByChoiceIDs = `-- name: GetConsequencesByChoiceIDs :many

SELECT
    choice_id,
    keys,
    value
FROM consequences
WHERE choice_id = ANY($1::uuid[])
`

type GetConsequencesByChoiceIDsRow struct {
	ChoiceID uuid.UUID
	Keys     string
	Value    bool
}

func (q *Queries) GetConsequencesByChoiceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetConsequencesByChoiceIDsRow, error) {
	rows, err := q.db.Query(ctx, getConsequencesByChoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConsequencesByChoiceIDsRow
	for rows.Next() {
		var i GetConsequencesByChoiceIDsRow
		if err := rows.Scan(&i.ChoiceID, &i.Keys, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExplanationsByChoiceIDs = `-- name: GetExplanationsByChoiceIDs :many

SELECT
    choice_id,
    level,
    content
FROM explanations
WHERE choice_id = ANY($1::uuid[])
`

type GetExplanationsByChoiceIDsRow struct {
	ChoiceID uuid.UUID
	Level    ExplanationLevel
	Content  string
}

func (q *Queries) GetExplanationsByChoiceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetExplanationsByChoiceIDsRow, error) {
	rows, err := q.db.Query(ctx, getExplanationsByChoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExplanationsByChoiceIDsRow
	for rows.Next() {
		var i GetExplanationsByChoiceIDsRow
		if err := rows.Scan(&i.ChoiceID, &i.Level, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImpactsByChoiceIDs = `-- name: GetImpactsByChoiceIDs :many

SELECT
    choice_id,
    metric,
    type,
    value
FROM impacts
WHERE choice_id = ANY($1::uuid[])
`

type GetImpactsByChoiceIDsRow struct {
	ChoiceID uuid.UUID
	Metric   ImpactMetric
	Type     ImpactType
	Value    float64
}

func (q *Queries) GetImpactsByChoiceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetImpactsByChoiceIDsRow, error) {
	rows, err := q.db.Query(ctx, getImpactsByChoiceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImpactsByChoiceIDsRow
	for rows.Next() {
		var i GetImpactsByChoiceIDsRow
		if err := rows.Scan(
			&i.ChoiceID,
			&i.Metric,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenario = `-- name: GetScenario :one

SELECT
    id,
    title,
    description,
    start_step_id
FROM scenarios
WHERE id =$1::uuid
`

type GetScenarioRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
}

func (q *Queries) GetScenario(ctx context.Context, dollar_1 uuid.UUID) (GetScenarioRow, error) {
	row := q.db.QueryRow(ctx, getScenario, dollar_1)
	var i GetScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartStepID,
	)
	return i, err
}

const getStepsByScenario = `-- name: GetStepsByScenario :many

SELECT
    id,
    question,
    context
FROM steps
WHERE scenario_id = $1::uuid
`

type GetStepsByScenarioRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsByScenario(ctx context.Context, dollar_1 uuid.UUID) ([]GetStepsByScenarioRow, error) {
	rows, err := q.db.Query(ctx, getStepsByScenario, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByScenarioRow
	for rows.Next() {
		var i GetStepsByScenarioRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
