// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenario.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countScenarios = `-- name: CountScenarios :one
SELECT COUNT(*) FROM scenarios
`

func (q *Queries) CountScenarios(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countScenarios)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScenario = `-- name: CreateScenario :one

INSERT INTO scenarios (id, title, description, difficulty)
VALUES ($1::uuid, $2, $3, $4)
RETURNING id, title, description, start_step_id, difficulty
`

type CreateScenarioParams struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	Difficulty  DifficultyLevel
}

type CreateScenarioRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
	Difficulty  DifficultyLevel
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (CreateScenarioRow, error) {
	row := q.db.QueryRow(ctx, createScenario,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
	)
	var i CreateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartStepID,
		&i.Difficulty,
	)
	return i, err
}

const deleteScenario = `-- name: DeleteScenario :exec
DELETE FROM scenarios
WHERE id = $1::uuid
`

func (q *Queries) DeleteScenario(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScenario, dollar_1)
	return err
}

const getScenario = `-- name: GetScenario :one
SELECT
    id,
    title,
    description,
    start_step_id,
    difficulty,
    time_limit_seconds
FROM scenarios
WHERE id = $1::uuid
`

type GetScenarioRow struct {
	ID               uuid.UUID
	Title            string
	Description      pgtype.Text
	StartStepID      uuid.UUID
	Difficulty       DifficultyLevel
	TimeLimitSeconds pgtype.Int4
}

func (q *Queries) GetScenario(ctx context.Context, dollar_1 uuid.UUID) (GetScenarioRow, error) {
	row := q.db.QueryRow(ctx, getScenario, dollar_1)
	var i GetScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartStepID,
		&i.Difficulty,
		&i.TimeLimitSeconds,
	)
	return i, err
}

const getScenarios = `-- name: GetScenarios :many

SELECT
    id,
    title,
    description,
    start_step_id
FROM scenarios
ORDER BY created_at DESC
`

type GetScenariosRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
}

func (q *Queries) GetScenarios(ctx context.Context) ([]GetScenariosRow, error) {
	rows, err := q.db.Query(ctx, getScenarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScenariosRow
	for rows.Next() {
		var i GetScenariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartStepID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenariosPaginated = `-- name: ListScenariosPaginated :many
SELECT id, title, description, start_step_id, difficulty, time_limit_seconds, created_at
FROM scenarios
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListScenariosPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListScenariosPaginated(ctx context.Context, arg ListScenariosPaginatedParams) ([]Scenario, error) {
	rows, err := q.db.Query(ctx, listScenariosPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scenario
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartStepID,
			&i.Difficulty,
			&i.TimeLimitSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScenario = `-- name: UpdateScenario :one

UPDATE scenarios
SET title = $2, description = $3, start_step_id = $4, difficulty = $5
WHERE id = $1::uuid
RETURNING id, title, description, start_step_id, difficulty
`

type UpdateScenarioParams struct {
	Column1     uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
	Difficulty  DifficultyLevel
}

type UpdateScenarioRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
	Difficulty  DifficultyLevel
}

func (q *Queries) UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (UpdateScenarioRow, error) {
	row := q.db.QueryRow(ctx, updateScenario,
		arg.Column1,
		arg.Title,
		arg.Description,
		arg.StartStepID,
		arg.Difficulty,
	)
	var i UpdateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartStepID,
		&i.Difficulty,
	)
	return i, err
}

const updateStartStep = `-- name: UpdateStartStep :one
UPDATE scenarios
SET start_step_id = $2
WHERE id = $1::uuid
RETURNING id, title, description, start_step_id, difficulty
`

type UpdateStartStepParams struct {
	Column1     uuid.UUID
	StartStepID uuid.UUID
}

type UpdateStartStepRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	StartStepID uuid.UUID
	Difficulty  DifficultyLevel
}

func (q *Queries) UpdateStartStep(ctx context.Context, arg UpdateStartStepParams) (UpdateStartStepRow, error) {
	row := q.db.QueryRow(ctx, updateStartStep, arg.Column1, arg.StartStepID)
	var i UpdateStartStepRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartStepID,
		&i.Difficulty,
	)
	return i, err
}
