// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStep = `-- name: CreateStep :one
INSERT INTO steps (id, scenario_id, question, context, order_index)
VALUES ($1::uuid, $2::uuid, $3, $4, $5)
RETURNING id, scenario_id, question, context, order_index, created_at
`

type CreateStepParams struct {
	Column1    uuid.UUID
	Column2    uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (Step, error) {
	row := q.db.QueryRow(ctx, createStep,
		arg.Column1,
		arg.Column2,
		arg.Question,
		arg.Context,
		arg.OrderIndex,
	)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Question,
		&i.Context,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStep = `-- name: DeleteStep :exec
DELETE FROM steps
WHERE id = $1::uuid
`

func (q *Queries) DeleteStep(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStep, dollar_1)
	return err
}

const getStepsByScenario = `-- name: GetStepsByScenario :many

SELECT
    id,
    question,
    context
FROM steps
WHERE scenario_id = $1::uuid
`

type GetStepsByScenarioRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsByScenario(ctx context.Context, dollar_1 uuid.UUID) ([]GetStepsByScenarioRow, error) {
	rows, err := q.db.Query(ctx, getStepsByScenario, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByScenarioRow
	for rows.Next() {
		var i GetStepsByScenarioRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepsByScenarioPaginated = `-- name: GetStepsByScenarioPaginated :many
SELECT
    id,
    question,
    context
FROM steps
WHERE scenario_id = $1::uuid
ORDER BY order_index
LIMIT $2 OFFSET $3
`

type GetStepsByScenarioPaginatedParams struct {
	Column1 uuid.UUID
	Limit   int32
	Offset  int32
}

type GetStepsByScenarioPaginatedRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsByScenarioPaginated(ctx context.Context, arg GetStepsByScenarioPaginatedParams) ([]GetStepsByScenarioPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getStepsByScenarioPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByScenarioPaginatedRow
	for rows.Next() {
		var i GetStepsByScenarioPaginatedRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepsPaginated = `-- name: GetStepsPaginated :many
SELECT
    id,
    question,
    context
FROM steps
ORDER BY order_index
LIMIT $1 OFFSET $2
`

type GetStepsPaginatedParams struct {
	Limit  int32
	Offset int32
}

type GetStepsPaginatedRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsPaginated(ctx context.Context, arg GetStepsPaginatedParams) ([]GetStepsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getStepsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsPaginatedRow
	for rows.Next() {
		var i GetStepsPaginatedRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStep = `-- name: UpdateStep :one
UPDATE steps
SET question = $2, context = $3, order_index = $4
WHERE id = $1::uuid
RETURNING id, scenario_id, question, context, order_index, created_at
`

type UpdateStepParams struct {
	Column1    uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (Step, error) {
	row := q.db.QueryRow(ctx, updateStep,
		arg.Column1,
		arg.Question,
		arg.Context,
		arg.OrderIndex,
	)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Question,
		&i.Context,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}
