// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSteps = `-- name: CountSteps :one
SELECT COUNT(*) FROM steps
`

func (q *Queries) CountSteps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSteps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStep = `-- name: CreateStep :one
INSERT INTO steps (id, scenario_id, question, context, order_index)
VALUES ($1::uuid, $2::uuid, $3, $4, $5)
RETURNING id, scenario_id, question, context, order_index, created_at
`

type CreateStepParams struct {
	Column1    uuid.UUID
	Column2    uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (Step, error) {
	row := q.db.QueryRow(ctx, createStep,
		arg.Column1,
		arg.Column2,
		arg.Question,
		arg.Context,
		arg.OrderIndex,
	)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Question,
		&i.Context,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStep = `-- name: DeleteStep :exec
DELETE FROM steps
WHERE id = $1::uuid
`

func (q *Queries) DeleteStep(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStep, dollar_1)
	return err
}

const existsStepOrderIndex = `-- name: ExistsStepOrderIndex :one
SELECT EXISTS(
    SELECT 1
    FROM steps
    WHERE scenario_id = $1::uuid
    AND order_index = $2
)
`

type ExistsStepOrderIndexParams struct {
	Column1    uuid.UUID
	OrderIndex int32
}

func (q *Queries) ExistsStepOrderIndex(ctx context.Context, arg ExistsStepOrderIndexParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsStepOrderIndex, arg.Column1, arg.OrderIndex)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getStep = `-- name: GetStep :one
SELECT
    id,
    scenario_id,
    question,
    context,
    order_index
FROM steps
WHERE id = $1::uuid
`

type GetStepRow struct {
	ID         uuid.UUID
	ScenarioID uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
}

func (q *Queries) GetStep(ctx context.Context, dollar_1 uuid.UUID) (GetStepRow, error) {
	row := q.db.QueryRow(ctx, getStep, dollar_1)
	var i GetStepRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Question,
		&i.Context,
		&i.OrderIndex,
	)
	return i, err
}

const getStepsByIDs = `-- name: GetStepsByIDs :many
SELECT 
    id,
    scenario_id,
    question,
    context,
    order_index
FROM steps
WHERE id IN ($1::uuid[])
ORDER BY order_index
`

type GetStepsByIDsRow struct {
	ID         uuid.UUID
	ScenarioID uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
}

func (q *Queries) GetStepsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetStepsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getStepsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByIDsRow
	for rows.Next() {
		var i GetStepsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.Question,
			&i.Context,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepsByScenario = `-- name: GetStepsByScenario :many
SELECT
    id,
    question,
    context
FROM steps
WHERE scenario_id = $1::uuid
`

type GetStepsByScenarioRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsByScenario(ctx context.Context, dollar_1 uuid.UUID) ([]GetStepsByScenarioRow, error) {
	rows, err := q.db.Query(ctx, getStepsByScenario, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByScenarioRow
	for rows.Next() {
		var i GetStepsByScenarioRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepsByScenarioPaginated = `-- name: GetStepsByScenarioPaginated :many
SELECT
    id,
    question,
    context
FROM steps
WHERE scenario_id = $1::uuid
ORDER BY order_index
LIMIT $2 OFFSET $3
`

type GetStepsByScenarioPaginatedParams struct {
	Column1 uuid.UUID
	Limit   int32
	Offset  int32
}

type GetStepsByScenarioPaginatedRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsByScenarioPaginated(ctx context.Context, arg GetStepsByScenarioPaginatedParams) ([]GetStepsByScenarioPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getStepsByScenarioPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByScenarioPaginatedRow
	for rows.Next() {
		var i GetStepsByScenarioPaginatedRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepsPaginated = `-- name: GetStepsPaginated :many
SELECT
    id,
    question,
    context
FROM steps
ORDER BY order_index
LIMIT $1 OFFSET $2
`

type GetStepsPaginatedParams struct {
	Limit  int32
	Offset int32
}

type GetStepsPaginatedRow struct {
	ID       uuid.UUID
	Question string
	Context  pgtype.Text
}

func (q *Queries) GetStepsPaginated(ctx context.Context, arg GetStepsPaginatedParams) ([]GetStepsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getStepsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsPaginatedRow
	for rows.Next() {
		var i GetStepsPaginatedRow
		if err := rows.Scan(&i.ID, &i.Question, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStartStepIfNull = `-- name: SetStartStepIfNull :exec
UPDATE scenarios
SET start_step_id = $2
WHERE
    id = $1::uuid
    AND start_step_id IS NULL
`

type SetStartStepIfNullParams struct {
	Column1     uuid.UUID
	StartStepID uuid.UUID
}

func (q *Queries) SetStartStepIfNull(ctx context.Context, arg SetStartStepIfNullParams) error {
	_, err := q.db.Exec(ctx, setStartStepIfNull, arg.Column1, arg.StartStepID)
	return err
}

const updateStep = `-- name: UpdateStep :one
UPDATE steps
SET question = $2, context = $3, order_index = $4
WHERE id = $1::uuid
RETURNING id, scenario_id, question, context, order_index, created_at
`

type UpdateStepParams struct {
	Column1    uuid.UUID
	Question   string
	Context    pgtype.Text
	OrderIndex int32
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (Step, error) {
	row := q.db.QueryRow(ctx, updateStep,
		arg.Column1,
		arg.Question,
		arg.Context,
		arg.OrderIndex,
	)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Question,
		&i.Context,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}
