// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_session.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserChoice = `-- name: CreateUserChoice :one
INSERT INTO user_choices (id, session_id, step_id, choice_id)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid)
RETURNING id, session_id, step_id, choice_id, created_at
`

type CreateUserChoiceParams struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	StepID    uuid.UUID
	ChoiceID  uuid.UUID
}

func (q *Queries) CreateUserChoice(ctx context.Context, arg CreateUserChoiceParams) (UserChoice, error) {
	row := q.db.QueryRow(ctx, createUserChoice,
		arg.ID,
		arg.SessionID,
		arg.StepID,
		arg.ChoiceID,
	)
	var i UserChoice
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StepID,
		&i.ChoiceID,
		&i.CreatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (id, user_id, scenario_id, current_step_id, metrics, flags, status)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5, $6, 'in_progress')
RETURNING id, user_id, scenario_id, current_step_id, metrics, flags, status, created_at
`

type CreateUserSessionParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ScenarioID    uuid.UUID
	CurrentStepID uuid.UUID
	Metrics       []byte
	Flags         []byte
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.ScenarioID,
		arg.CurrentStepID,
		arg.Metrics,
		arg.Flags,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScenarioID,
		&i.CurrentStepID,
		&i.Metrics,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserChoicesBySession = `-- name: GetUserChoicesBySession :many
SELECT id, session_id, step_id, choice_id, created_at
FROM user_choices
WHERE session_id = $1::uuid
ORDER BY created_at
`

func (q *Queries) GetUserChoicesBySession(ctx context.Context, dollar_1 uuid.UUID) ([]UserChoice, error) {
	rows, err := q.db.Query(ctx, getUserChoicesBySession, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChoice
	for rows.Next() {
		var i UserChoice
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StepID,
			&i.ChoiceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSession = `-- name: GetUserSession :one
SELECT id, user_id, scenario_id, current_step_id, metrics, flags, status, created_at FROM user_sessions
WHERE id = $1::uuid
`

func (q *Queries) GetUserSession(ctx context.Context, dollar_1 uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSession, dollar_1)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScenarioID,
		&i.CurrentStepID,
		&i.Metrics,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserSessionForUpdate = `-- name: GetUserSessionForUpdate :one
SELECT id, user_id, scenario_id, current_step_id, metrics, flags, status, created_at
FROM user_sessions
WHERE id = $1::uuid
FOR UPDATE
`

func (q *Queries) GetUserSessionForUpdate(ctx context.Context, dollar_1 uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionForUpdate, dollar_1)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScenarioID,
		&i.CurrentStepID,
		&i.Metrics,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, scenario_id, current_step_id, metrics, flags, status, created_at
FROM user_sessions
WHERE user_id = $1::uuid
ORDER BY created_at
`

func (q *Queries) ListSessionsByUserID(ctx context.Context, dollar_1 uuid.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScenarioID,
			&i.CurrentStepID,
			&i.Metrics,
			&i.Flags,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSession = `-- name: UpdateUserSession :one
UPDATE user_sessions
SET current_step_id = $1,
    metrics         = $2,
    flags           = $3,
    status          = $4
WHERE id = $5::uuid
RETURNING id, user_id, scenario_id, current_step_id, metrics, flags, status, created_at
`

type UpdateUserSessionParams struct {
	CurrentStepID uuid.UUID
	Metrics       []byte
	Flags         []byte
	Status        SessionStatus
	ID            uuid.UUID
}

func (q *Queries) UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, updateUserSession,
		arg.CurrentStepID,
		arg.Metrics,
		arg.Flags,
		arg.Status,
		arg.ID,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScenarioID,
		&i.CurrentStepID,
		&i.Metrics,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
